encodebot:
  hostname: encodebot
  build: ./encodebot
  ports:
  - 81:80
  volumes:
    - "./encodebot/www/:/var/www/"
    - "./encodebot/lighttpd/:/etc/lighttpd/"
  volumes_from:
    - plugins
    - uploads
  environment:
    ENCODE_ACCESS_KEY: testingtesting

wordpress:
  build: ./wordpress
  links:
    - db:mysql
  ports:
    - 80:80
  volumes:
  - "../../jonathancoulton-theme:/var/www/html/wp-content/themes/jonathancoulton-theme"
  - "./wordpress/wp-content/uploads:/var/www/html/wp-content/uploads"
  - "./wordpress/wp-content/plugins:/var/www/html/wp-content/plugins"
  - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: 1234

pma:
  build: ./pma
  links:
    - db:mysql
  ports:
    - 82:80
  environment:
    BLOWFISH_SECRET: testing
  volumes:
    - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
