encodebot:
  hostname: encodebot
  build: ./encodebot
  ports:
  - 81:80
  volumes:
    - "./encodebot/www/:/var/www/"
    - "./encodebot/lighttpd/:/etc/lighttpd/"
  environment:
    ENCODE_ACCESS_KEY: testingtesting

wordpress:
  build: ./wordpress
  links:
    - db:mysql
  ports:
    - 80:80
  volumes:
  - "../../jonathancoulton-theme:/var/www/html/wp-content/themes/jonathancoulton-theme"
  - "./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: pma
    MYSQL_PASSWORD: 1234

