<?php
/**
 * Created by PhpStorm.
 * User: DAM
 * Date: 7/31/15
 * Time: 17:16
 */
$encode_hash = $params['var'];
$encode_transient = get_transient($encode_hash);
if ($encode_transient) {
    $encode_details = explode("|", $encode_transient);
    $track_post_id = $encode_details[0];
    $encode_format = $encode_details[1];

    if (!function_exists('wp_handle_upload')) {
        require_once(ABSPATH . 'wp-admin/includes/file.php');
    } else {
        die("wp_handle_upload() doesn't exist!");
    }

    $uploadedfile = $_FILES['file'];

    $upload_overrides = array('test_form' => false);

    $movefile = wp_handle_upload($uploadedfile, $upload_overrides);

    if ($movefile && !isset($movefile['error'])) {
        echo "File is valid, and was successfully uploaded.\n";
        var_dump($movefile);
    } else {
        /**
         * Error generated by _wp_handle_upload()
         * @see _wp_handle_upload() in wp-admin/includes/file.php
         */
        echo $movefile['error'];
    }
}